import {
  ActivityMonitoringData,
  AlarmData,
  ListOfUnfulfilledDoorsData,
  NoPermitsData,
  RainFallData,
  WaterConditionData,
} from "./types";

export const dummyGates = [
  {
    nama: "BS6",
    TMA: "15",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "11"],
    status: "Terpenuhi",
  },
  {
    nama: "BS7",
    TMA: "12",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "20", "19"],
    status: "Terpenuhi",
  },
  {
    nama: "BS8",
    TMA: "10",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "18"],
    status: "Tidak Terpenuhi",
  },
  {
    nama: "BS9",
    TMA: "20",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "17"],
    status: "Terpenuhi",
  },
  {
    nama: "BS10",
    TMA: "15",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "16"],
    status: "Tidak Terpenuhi",
  },
  {
    nama: "BS6",
    TMA: "15",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "14"],
    status: "Terpenuhi",
  },
  {
    nama: "BS7",
    TMA: "12",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "13"],
    status: "Terpenuhi",
  },
  {
    nama: "BS8",
    TMA: "10",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "12"],
    status: "Tidak Terpenuhi",
  },
  {
    nama: "BS9",
    TMA: "20",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "11"],
    status: "Tidak Terpenuhi",
  },
  {
    nama: "BS10",
    TMA: "15",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "10"],
    status: "Terpenuhi",
  },
  {
    nama: "BS10",
    TMA: "15",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    saluran: "Cihaur",
    bukaanPintu: ["12", "15", "10"],
    status: "Terpenuhi",
  },
];

interface WaterChannels {
  id: string;
  totalCctv: number;
  tma: number;
  actualDebit: number;
  name: string;
  pch: unknown;
  hasOfflineSensor: boolean;
  totalOfficer: number;
  coordinates: {
    long: number;
    lat: number;
  };
}

export const waterways: WaterChannels[] = [
  {
    id: "1",
    coordinates: {
      lat: -7.53863800356091,
      long: 108.77437884524684,
    },
    name: "Citarum",
    totalCctv: 10,
    actualDebit: 10,
    totalOfficer: 10,
    tma: 10,
    hasOfflineSensor: false,
    pch: {},
  },
  {
    id: "2",
    coordinates: {
      lat: -7.5389, // Slightly north-east
      long: 108.7745,
    },
    name: "Ciliwung",
    totalCctv: 8,
    actualDebit: 9,
    totalOfficer: 7,
    tma: 8,
    hasOfflineSensor: true,
    pch: {},
  },
  {
    id: "3",
    coordinates: {
      lat: -7.5391, // Slightly north
      long: 108.7741,
    },
    name: "Cisadane",
    totalCctv: 7,
    actualDebit: 8,
    totalOfficer: 6,
    tma: 7,
    hasOfflineSensor: false,
    pch: {},
  },
  {
    id: "4",
    coordinates: {
      lat: -7.5384, // Slightly south-west
      long: 108.7738,
    },
    name: "Brantas",
    totalCctv: 9,
    actualDebit: 11,
    totalOfficer: 9,
    tma: 9,
    hasOfflineSensor: false,
    pch: {},
  },
  {
    id: "5",
    coordinates: {
      lat: -7.5379, // Slightly south-east
      long: 108.7748,
    },
    name: "Sungai Kapuas",
    totalCctv: 6,
    actualDebit: 5,
    totalOfficer: 5,
    tma: 6,
    hasOfflineSensor: true,
    pch: {},
  },
];

export const dummySchedules = [
  {
    date: "2021-10-01 08:00",
    watergateName: "BCK 1 KA",
    initialPosition: "12 cm",
    targetPosition: "15 cm",
    reason: "Kerusakan",
    type: "Terjadwal",
    officerName: "Irfan Aulia",
    status: "Terjadwal",
  },
  {
    date: "2021-10-02 10:30",
    watergateName: "BCK 2 KA",
    initialPosition: "10 cm",
    targetPosition: "13 cm",
    reason: "Perbaikan Rutin",
    type: "Terjadwal",
    officerName: "Ahmad Santoso",
    status: "Selesai",
  },
  {
    date: "2021-10-03 14:45",
    watergateName: "BCK 3 KA",
    initialPosition: "14 cm",
    targetPosition: "16 cm",
    reason: "Penyesuaian Debit",
    type: "Peringatan",
    officerName: "Dewi Putri",
    status: "Terjadwal",
  },
  {
    date: "2021-10-04 09:15",
    watergateName: "BCK 4 KA",
    initialPosition: "11 cm",
    targetPosition: "14 cm",
    reason: "Pembersihan",
    type: "Terjadwal",
    officerName: "Budi Pranata",
    status: "Dibatalkan",
  },
  {
    date: "2021-10-05 11:00",
    watergateName: "BCK 5 KA",
    initialPosition: "9 cm",
    targetPosition: "12 cm",
    reason: "Pemeliharaan",
    type: "Terjadwal",
    officerName: "Siti Nurhaliza",
    status: "Selesai",
  },
];

export const dummyAssets = [
  {
    id: "A001",
    name: "Laptop HP C1",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Rusak",
  },
  {
    id: "A002",
    name: "Laptop HP C2",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Aktif",
  },
  {
    id: "A003",
    name: "Laptop HP C3",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Aktif",
  },
  {
    id: "A004",
    name: "Laptop HP C4",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Rusak",
  },
  {
    id: "A005",
    name: "Laptop HP C5",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Rusak",
  },
  {
    id: "A006",
    name: "Laptop HP C6",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Aktif",
  },
  {
    id: "A007",
    name: "Laptop HP C7",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Aktif",
  },
  {
    id: "A008",
    name: "Laptop HP C8",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Rusak",
  },
  {
    id: "A009",
    name: "Laptop HP C9",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Aktif",
  },
  {
    id: "A010",
    name: "Laptop HP C10",
    responsibleOfficer: "Budi",
    location: "Command Center",
    status: "Rusak",
  },
];

export const infrastructures = [
  {
    id: "1",
    coordinates: {
      lat: -7.53863800356091,
      long: 108.77437884524684,
    },
    name: "Intake A",
    type: "Intake",
    pengelola: "Dinas PUPR",
    ws1: "Cihaur",
    ws2: "Cihaur",
    Provinsi: "Jawa Barat",
    Kabupaten: "Bandung",
    Kecamatan: "Cihaurbeuti",
    Desa: "Cihaurbeuti",
  },
  {
    id: "2",
    coordinates: {
      lat: -7.5389,
      long: 108.7745,
    },
    name: "Intake B",
    type: "Intake",
    pengelola: "Dinas PUPR",
    ws1: "Cihaur",
    ws2: "Cihaur",
    Provinsi: "Jawa Barat",
    Kabupaten: "Bandung",
    Kecamatan: "Cihaurbeuti",
    Desa: "Cihaurbeuti",
  },
  {
    id: "3",
    coordinates: {
      lat: -7.5391,
      long: 108.7741,
    },
    name: "Intake C",
    type: "Intake",
    pengelola: "Dinas PUPR",
    ws1: "Cihaur",
    ws2: "Cihaur",
    Provinsi: "Jawa Barat",
    Kabupaten: "Bandung",
    Kecamatan: "Cihaurbeuti",
    Desa: "Cihaurbeuti",
  },
  {
    id: "4",
    coordinates: {
      lat: -7.5384,
      long: 108.7738,
    },
    name: "Intake D",
    type: "Intake",
    pengelola: "Dinas PUPR",
    ws1: "Cihaur",
    ws2: "Cihaur",
    Provinsi: "Jawa Barat",
    Kabupaten: "Bandung",
    Kecamatan: "Cihaurbeuti",
    Desa: "Cihaurbeuti",
  },
  {
    id: "5",
    coordinates: {
      lat: -7.5379,
      long: 108.7748,
    },
    name: "Intake E",
    type: "Intake",
    pengelola: "Dinas PUPR",
    ws1: "Cihaur",
    ws2: "Cihaur",
    Provinsi: "Jawa Barat",
    Kabupaten: "Bandung",
    Kecamatan: "Cihaurbeuti",
    Desa: "Cihaurbeuti",
  },
];

export const infrastructures2 = {
  intake: [
    {
      id: "1",
      coordinates: {
        lat: -7.53863800356091,
        long: 108.77437884524684,
      },
      name: "Intake A",
    },
    {
      id: "2",
      coordinates: {
        lat: -7.5389,
        long: 108.7745,
      },
      name: "Intake B",
    },
    {
      id: "3",
      coordinates: {
        lat: -7.5391,
        long: 108.7741,
      },
      name: "Intake C",
    },
    {
      id: "4",
      coordinates: {
        lat: -7.5384,
        long: 108.7738,
      },
      name: "Intake D",
    },
    {
      id: "5",
      coordinates: {
        lat: -7.5379,
        long: 108.7748,
      },
      name: "Intake E",
    },
  ],
  bendung: [
    {
      id: "1",
      coordinates: {
        lat: -7.54,
        long: 108.775,
      },
      name: "Bendung A",
    },
    {
      id: "2",
      coordinates: {
        lat: -7.5401,
        long: 108.7751,
      },
      name: "Bendung B",
    },
    {
      id: "3",
      coordinates: {
        lat: -7.5402,
        long: 108.7752,
      },
      name: "Bendung C",
    },
    {
      id: "4",
      coordinates: {
        lat: -7.5403,
        long: 108.7753,
      },
      name: "Bendung D",
    },
    {
      id: "5",
      coordinates: {
        lat: -7.5404,
        long: 108.7754,
      },
      name: "Bendung E",
    },
  ],
  embung: [
    {
      id: "1",
      coordinates: {
        lat: -7.541,
        long: 108.776,
      },
      name: "Embung A",
    },
    {
      id: "2",
      coordinates: {
        lat: -7.5411,
        long: 108.7761,
      },
      name: "Embung B",
    },
    {
      id: "3",
      coordinates: {
        lat: -7.5412,
        long: 108.7762,
      },
      name: "Embung C",
    },
    {
      id: "4",
      coordinates: {
        lat: -7.5413,
        long: 108.7763,
      },
      name: "Embung D",
    },
    {
      id: "5",
      coordinates: {
        lat: -7.5414,
        long: 108.7764,
      },
      name: "Embung E",
    },
  ],
};

export const dummyAlarms: AlarmData[] = [
  {
    id: 1,
    saluran: "Cihaur",
    pintu: "BCK 1 KA",
    prioritas: "Kritis",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "0821863297198"],
  },
  {
    id: 2,
    saluran: "Cihaur",
    pintu: "BCK 2 KA",
    prioritas: "Peringatan",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Notifikasi Dashboard", "0821863297198"],
  },
  {
    id: 3,
    saluran: "Cihaur",
    pintu: "BCK 3 KA",
    prioritas: "Kritis",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
  {
    id: 4,
    saluran: "Cihaur",
    pintu: "BCK 4 KA",
    prioritas: "Kritis",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam"],
  },
  {
    id: 5,
    saluran: "Cihaur",
    pintu: "BCK 5 KA",
    prioritas: "Peringatan",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
  {
    id: 6,
    saluran: "Cihaur",
    pintu: "BCK 6 KA",
    prioritas: "Peringatan",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
  {
    id: 7,
    saluran: "Cihaur",
    pintu: "BCK 7 KA",
    prioritas: "Kritis",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
  {
    id: 8,
    saluran: "Cihaur",
    pintu: "BCK 8 KA",
    prioritas: "Kritis",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
  {
    id: 9,
    saluran: "Cihaur",
    pintu: "BCK 9 KA",
    prioritas: "Kritis",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
  {
    id: 10,
    saluran: "Cihaur",
    pintu: "BCK 10 KA",
    prioritas: "Peringatan",
    kondisi: "<= 40 Selama 50 Menit",
    penerima: ["Adam", "Hawa"],
  },
];

export const dummyWaterConditions: WaterConditionData[] = [
  {
    saluran: "Cihaur",
    tma: "12",
    debitAktual: "24132.10",
    debitKebutuhan: "52132.30",
    status: "Tidak Terpenuhi",
  },
  {
    saluran: "Ciliwung",
    tma: "10",
    debitAktual: "23132.10",
    debitKebutuhan: "51132.30",
    status: "Terpenuhi",
  },
  {
    saluran: "Cisadane",
    tma: "15",
    debitAktual: "25132.10",
    debitKebutuhan: "53132.30",
    status: "Tidak Terpenuhi",
  },
  {
    saluran: "Brantas",
    tma: "8",
    debitAktual: "22132.10",
    debitKebutuhan: "50132.30",
    status: "Terpenuhi",
  },
  {
    saluran: "Sungai Kapuas",
    tma: "20",
    debitAktual: "26132.10",
    debitKebutuhan: "54132.30",
    status: "Tidak Terpenuhi",
  },
];

export const dummyListOfUnfulfilledDoors: ListOfUnfulfilledDoorsData[] = [
  {
    name: "BCK 1 KA",
    tma: 20,
    actual_debit: 30,
    debit_needs: 546128.4568,
    channel_name: "Cihaur",
    door_opening: ["12", "15", "11"],
    status: "Tidak Terpenuhi",
  },
  {
    name: "BCK 2 KA",
    tma: 18,
    actual_debit: 28,
    debit_needs: 546128.4568,
    channel_name: "Ciliwung",
    door_opening: ["10", "13", "12"],
    status: "Tidak Terpenuhi",
  },
  {
    name: "BCK 3 KA",
    tma: 22,
    actual_debit: 32,
    debit_needs: 546128.4568,
    channel_name: "Cisadane",
    door_opening: ["11", "14", "13"],
    status: "Tidak Terpenuhi",
  },
  {
    name: "BCK 4 KA",
    tma: 19,
    actual_debit: 29,
    debit_needs: 546128.4568,
    channel_name: "Brantas",
    door_opening: ["12", "15", "14"],
    status: "Tidak Terpenuhi",
  },
  {
    name: "BCK 5 KA",
    tma: 21,
    actual_debit: 31,
    debit_needs: 546128.4568,
    channel_name: "Sungai Kapuas",
    door_opening: ["13", "16", "15"],
    status: "Tidak Terpenuhi",
  },
];

export const dummyActivityMonitorings: ActivityMonitoringData[] = [
  {
    date: "25/09/2024 13:45 WIB",
    type: "Pintu Air",
    activity: "Randi menaikan Pintu BSP 3 Kiri sebanyak 6 cm",
  },
  {
    date: "26/09/2024 09:30 WIB",
    type: "Pintu Air",
    activity: "Siti menurunkan Pintu BSP 4 Kiri sebanyak 4 cm",
  },
  {
    date: "27/09/2024 11:00 WIB",
    type: "Pintu Air",
    activity: "Budi menaikan Pintu BSP 5 Kiri sebanyak 5 cm",
  },
  {
    date: "28/09/2024 15:20 WIB",
    type: "Pintu Air",
    activity: "Andi menurunkan Pintu BSP 6 Kiri sebanyak 3 cm",
  },
  {
    date: "29/09/2024 10:10 WIB",
    type: "Pintu Air",
    activity: "Dewi menaikan Pintu BSP 7 Kiri sebanyak 2 cm",
  },
  {
    date: "30/09/2024 14:00 WIB",
    type: "Pintu Air",
    activity: "Eko menurunkan Pintu BSP 8 Kiri sebanyak 6 cm",
  },
  {
    date: "01/10/2024 08:45 WIB",
    type: "Pintu Air",
    activity: "Fajar menaikan Pintu BSP 9 Kiri sebanyak 7 cm",
  },
  {
    date: "02/10/2024 12:30 WIB",
    type: "Pintu Air",
    activity: "Gina menurunkan Pintu BSP 10 Kiri sebanyak 8 cm",
  },
];

export const dummyRainFallData: RainFallData[] = [
  {
    id: "1",
    nama: "Cijalu",
    manual: 10,
    tipe: "Curah Hujan",
    telemetri: 99.99,
    kondisi: "Hujan Lebat 15.7",
    penyedia: "Luwes",
    sejak: "1989",
    tertinggi: "215mm 5/Okt/2021",
    petugas: "Budi",
    no_hp: "08123456789",
    elevasi: "100 mdpl",
    coordinates: {
      lat: -7.53863800356091,
      long: 108.77437884524684,
    },
  },
  {
    id: "2",
    nama: "Cikapundung",
    manual: 15,
    tipe: "Curah Hujan",
    telemetri: 89.99,
    kondisi: "Hujan Sedang 10.5",
    penyedia: "Luwes",
    sejak: "1990",
    tertinggi: "200mm 6/Okt/2021",
    petugas: "Andi",
    no_hp: "08123456780",
    elevasi: "150 mdpl",
    coordinates: {
      lat: -7.5389,
      long: 108.7745,
    },
  },
  {
    id: "3",
    nama: "Cisangkuy",
    manual: 20,
    tipe: "Curah Hujan",
    telemetri: 79.99,
    kondisi: "Hujan Ringan 5.3",
    penyedia: "Luwes",
    sejak: "1991",
    tertinggi: "180mm 7/Okt/2021",
    petugas: "Siti",
    no_hp: "08123456781",
    elevasi: "200 mdpl",
    coordinates: {
      lat: -7.5391,
      long: 108.7741,
    },
  },
  {
    id: "4",
    nama: "Citarik",
    manual: 25,
    tipe: "Curah Hujan",
    telemetri: 69.99,
    kondisi: "Hujan Lebat 20.1",
    penyedia: "Luwes",
    sejak: "1992",
    tertinggi: "220mm 8/Okt/2021",
    petugas: "Bambang",
    no_hp: "08123456782",
    elevasi: "250 mdpl",
    coordinates: {
      lat: -7.5384,
      long: 108.7738,
    },
  },
  {
    id: "5",
    nama: "Cisadane",
    manual: 30,
    tipe: "Curah Hujan",
    telemetri: 59.99,
    kondisi: "Hujan Sedang 15.2",
    penyedia: "Luwes",
    sejak: "1993",
    tertinggi: "210mm 9/Okt/2021",
    petugas: "Dewi",
    no_hp: "08123456783",
    elevasi: "300 mdpl",
    coordinates: {
      lat: -7.5379,
      long: 108.7748,
    },
  },
  {
    id: "6",
    nama: "Ciliwung",
    manual: 35,
    tipe: "Curah Hujan",
    telemetri: 49.99,
    kondisi: "Hujan Ringan 10.4",
    penyedia: "Luwes",
    sejak: "1994",
    tertinggi: "190mm 10/Okt/2021",
    petugas: "Eko",
    no_hp: "08123456784",
    elevasi: "350 mdpl",
    coordinates: {
      lat: -7.541,
      long: 108.776,
    },
  },
  {
    id: "7",
    nama: "Cimandiri",
    manual: 40,
    tipe: "Curah Hujan",
    telemetri: 39.99,
    kondisi: "Hujan Lebat 25.6",
    penyedia: "Luwes",
    sejak: "1995",
    tertinggi: "230mm 11/Okt/2021",
    petugas: "Fajar",
    no_hp: "08123456785",
    elevasi: "400 mdpl",
    coordinates: {
      lat: -7.5411,
      long: 108.7761,
    },
  },
  {
    id: "8",
    nama: "Cimanuk",
    manual: 45,
    tipe: "Curah Hujan",
    telemetri: 29.99,
    kondisi: "Hujan Sedang 20.7",
    penyedia: "Luwes",
    sejak: "1996",
    tertinggi: "240mm 12/Okt/2021",
    petugas: "Gita",
    no_hp: "08123456786",
    elevasi: "450 mdpl",
    coordinates: {
      lat: -7.5412,
      long: 108.7762,
    },
  },
  {
    id: "9",
    nama: "Cipamingkis",
    manual: 50,
    tipe: "Curah Hujan",
    telemetri: 19.99,
    kondisi: "Hujan Ringan 15.8",
    penyedia: "Luwes",
    sejak: "1997",
    tertinggi: "250mm 13/Okt/2021",
    petugas: "Hadi",
    no_hp: "08123456787",
    elevasi: "500 mdpl",
    coordinates: {
      lat: -7.5413,
      long: 108.7763,
    },
  },
  {
    id: "10",
    nama: "Cipinang",
    manual: 55,
    tipe: "Curah Hujan",
    telemetri: 9.99,
    kondisi: "Hujan Lebat 30.9",
    penyedia: "Luwes",
    sejak: "1998",
    tertinggi: "260mm 14/Okt/2021",
    petugas: "Indra",
    no_hp: "08123456788",
    elevasi: "550 mdpl",
    coordinates: {
      lat: -7.5414,
      long: 108.7764,
    },
  },
];

export const dummyNoPermits: NoPermitsData[] = [
  {
    id: "1",
    date: "2024-12-12",
    coordinates: {
      lat: -7.23,
      long: 108.3214,
    },
    image: "/src/assets/drone.svg",
    type: "Jembatan",
  },
  {
    id: "2",
    date: "2024-12-12",
    coordinates: {
      lat: -7.23,
      long: 108.3214,
    },
    image: "/src/assets/drone.svg",
    type: "Jembatan",
  },
  {
    id: "3",
    date: "2024-12-12",
    coordinates: {
      lat: -7.23,
      long: 108.3214,
    },
    image: "/src/assets/drone.svg",
    type: "Jembatan",
  },
  {
    id: "4",
    date: "2024-12-13",
    coordinates: {
      lat: -7.24,
      long: 108.3224,
    },
    image: "/src/assets/drone.svg",
    type: "Intake",
  },
  {
    id: "5",
    date: "2024-12-14",
    coordinates: {
      lat: -7.25,
      long: 108.3234,
    },
    image: "/src/assets/drone.svg",
    type: "Intake",
  },
  {
    id: "6",
    date: "2024-12-15",
    coordinates: {
      lat: -7.26,
      long: 108.3244,
    },
    image: "/src/assets/drone.svg",
    type: "Jembatan",
  },
  {
    id: "7",
    date: "2024-12-16",
    coordinates: {
      lat: -7.27,
      long: 108.3254,
    },
    image: "/src/assets/drone.svg",
    type: "Bendungan",
  },
  {
    id: "8",
    date: "2024-12-17",
    coordinates: {
      lat: -7.28,
      long: 108.3264,
    },
    image: "/src/assets/drone.svg",
    type: "Pipa",
  },
  {
    id: "9",
    date: "2024-12-18",
    coordinates: {
      lat: -7.29,
      long: 108.3274,
    },
    image: "/src/assets/drone.svg",
    type: "Bendung",
  },
  {
    id: "10",
    date: "2024-12-19",
    coordinates: {
      lat: -7.3,
      long: 108.3284,
    },
    image: "/src/assets/drone.svg",
    type: "Intake",
  },
];
