/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as Sijagacai2Import } from './routes/sijagacai2'
import { Route as SetPasswordPinImport } from './routes/set-password-pin'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ProjectsDataImport } from './routes/projects-data'
import { Route as PermitsDataImport } from './routes/permits-data'
import { Route as MasterDataImport } from './routes/master-data'
import { Route as MapImport } from './routes/map'
import { Route as LoginImport } from './routes/login'
import { Route as JdihImport } from './routes/jdih'
import { Route as InfrastructureImport } from './routes/infrastructure'
import { Route as EmployeesDataImport } from './routes/employees-data'
import { Route as ChangePinImport } from './routes/change-pin'
import { Route as ChangePasswordImport } from './routes/change-password'
import { Route as AssetsDataImport } from './routes/assets-data'
import { Route as AlarmHistoryImport } from './routes/alarm-history'
import { Route as AiConfigurationImport } from './routes/ai-configuration'
import { Route as IndexImport } from './routes/index'
import { Route as WaterQualityIndexImport } from './routes/water-quality/index'
import { Route as WaterGateIndexImport } from './routes/water-gate/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as SijagacaiIndexImport } from './routes/sijagacai/index'
import { Route as WaterGateWatergateIdImport } from './routes/water-gate/$watergateId'
import { Route as SijagacaiSijagacaiIdImport } from './routes/sijagacai/$sijagacaiId'
import { Route as AlertSystemHistoryImport } from './routes/alert-system/history'
import { Route as AlertSystemConfigurationImport } from './routes/alert-system/configuration'
import { Route as HidrologyWaterLevelIndexImport } from './routes/hidrology/water-level/index'
import { Route as HidrologyRainfallIndexImport } from './routes/hidrology/rainfall/index'
import { Route as HidrologyClimatologyIndexImport } from './routes/hidrology/climatology/index'
import { Route as SijagacaiLaporanPemantauanLaporanidImport } from './routes/sijagacai/laporan-pemantauan/$laporanid'
import { Route as HidrologyWaterLevelWaterlevelIdImport } from './routes/hidrology/water-level/$waterlevelId'
import { Route as HidrologyRainfallRainfallIdImport } from './routes/hidrology/rainfall/$rainfallId'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const WelcomeRoute = WelcomeImport.update({
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const Sijagacai2Route = Sijagacai2Import.update({
  path: '/sijagacai2',
  getParentRoute: () => rootRoute,
} as any)

const SetPasswordPinRoute = SetPasswordPinImport.update({
  path: '/set-password-pin',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsDataRoute = ProjectsDataImport.update({
  path: '/projects-data',
  getParentRoute: () => rootRoute,
} as any)

const PermitsDataRoute = PermitsDataImport.update({
  path: '/permits-data',
  getParentRoute: () => rootRoute,
} as any)

const MasterDataRoute = MasterDataImport.update({
  path: '/master-data',
  getParentRoute: () => rootRoute,
} as any)

const MapRoute = MapImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const JdihRoute = JdihImport.update({
  path: '/jdih',
  getParentRoute: () => rootRoute,
} as any)

const InfrastructureRoute = InfrastructureImport.update({
  path: '/infrastructure',
  getParentRoute: () => rootRoute,
} as any)

const EmployeesDataRoute = EmployeesDataImport.update({
  path: '/employees-data',
  getParentRoute: () => rootRoute,
} as any)

const ChangePinRoute = ChangePinImport.update({
  path: '/change-pin',
  getParentRoute: () => rootRoute,
} as any)

const ChangePasswordRoute = ChangePasswordImport.update({
  path: '/change-password',
  getParentRoute: () => rootRoute,
} as any)

const AssetsDataRoute = AssetsDataImport.update({
  path: '/assets-data',
  getParentRoute: () => rootRoute,
} as any)

const AlarmHistoryRoute = AlarmHistoryImport.update({
  path: '/alarm-history',
  getParentRoute: () => rootRoute,
} as any)

const AiConfigurationRoute = AiConfigurationImport.update({
  path: '/ai-configuration',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WaterQualityIndexRoute = WaterQualityIndexImport.update({
  path: '/water-quality/',
  getParentRoute: () => rootRoute,
} as any)

const WaterGateIndexRoute = WaterGateIndexImport.update({
  path: '/water-gate/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const SijagacaiIndexRoute = SijagacaiIndexImport.update({
  path: '/sijagacai/',
  getParentRoute: () => rootRoute,
} as any)

const WaterGateWatergateIdRoute = WaterGateWatergateIdImport.update({
  path: '/water-gate/$watergateId',
  getParentRoute: () => rootRoute,
} as any)

const SijagacaiSijagacaiIdRoute = SijagacaiSijagacaiIdImport.update({
  path: '/sijagacai/$sijagacaiId',
  getParentRoute: () => rootRoute,
} as any)

const AlertSystemHistoryRoute = AlertSystemHistoryImport.update({
  path: '/alert-system/history',
  getParentRoute: () => rootRoute,
} as any)

const AlertSystemConfigurationRoute = AlertSystemConfigurationImport.update({
  path: '/alert-system/configuration',
  getParentRoute: () => rootRoute,
} as any)

const HidrologyWaterLevelIndexRoute = HidrologyWaterLevelIndexImport.update({
  path: '/hidrology/water-level/',
  getParentRoute: () => rootRoute,
} as any)

const HidrologyRainfallIndexRoute = HidrologyRainfallIndexImport.update({
  path: '/hidrology/rainfall/',
  getParentRoute: () => rootRoute,
} as any)

const HidrologyClimatologyIndexRoute = HidrologyClimatologyIndexImport.update({
  path: '/hidrology/climatology/',
  getParentRoute: () => rootRoute,
} as any)

const SijagacaiLaporanPemantauanLaporanidRoute =
  SijagacaiLaporanPemantauanLaporanidImport.update({
    path: '/sijagacai/laporan-pemantauan/$laporanid',
    getParentRoute: () => rootRoute,
  } as any)

const HidrologyWaterLevelWaterlevelIdRoute =
  HidrologyWaterLevelWaterlevelIdImport.update({
    path: '/hidrology/water-level/$waterlevelId',
    getParentRoute: () => rootRoute,
  } as any)

const HidrologyRainfallRainfallIdRoute =
  HidrologyRainfallRainfallIdImport.update({
    path: '/hidrology/rainfall/$rainfallId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ai-configuration': {
      id: '/ai-configuration'
      path: '/ai-configuration'
      fullPath: '/ai-configuration'
      preLoaderRoute: typeof AiConfigurationImport
      parentRoute: typeof rootRoute
    }
    '/alarm-history': {
      id: '/alarm-history'
      path: '/alarm-history'
      fullPath: '/alarm-history'
      preLoaderRoute: typeof AlarmHistoryImport
      parentRoute: typeof rootRoute
    }
    '/assets-data': {
      id: '/assets-data'
      path: '/assets-data'
      fullPath: '/assets-data'
      preLoaderRoute: typeof AssetsDataImport
      parentRoute: typeof rootRoute
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/change-pin': {
      id: '/change-pin'
      path: '/change-pin'
      fullPath: '/change-pin'
      preLoaderRoute: typeof ChangePinImport
      parentRoute: typeof rootRoute
    }
    '/employees-data': {
      id: '/employees-data'
      path: '/employees-data'
      fullPath: '/employees-data'
      preLoaderRoute: typeof EmployeesDataImport
      parentRoute: typeof rootRoute
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureImport
      parentRoute: typeof rootRoute
    }
    '/jdih': {
      id: '/jdih'
      path: '/jdih'
      fullPath: '/jdih'
      preLoaderRoute: typeof JdihImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataImport
      parentRoute: typeof rootRoute
    }
    '/permits-data': {
      id: '/permits-data'
      path: '/permits-data'
      fullPath: '/permits-data'
      preLoaderRoute: typeof PermitsDataImport
      parentRoute: typeof rootRoute
    }
    '/projects-data': {
      id: '/projects-data'
      path: '/projects-data'
      fullPath: '/projects-data'
      preLoaderRoute: typeof ProjectsDataImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/set-password-pin': {
      id: '/set-password-pin'
      path: '/set-password-pin'
      fullPath: '/set-password-pin'
      preLoaderRoute: typeof SetPasswordPinImport
      parentRoute: typeof rootRoute
    }
    '/sijagacai2': {
      id: '/sijagacai2'
      path: '/sijagacai2'
      fullPath: '/sijagacai2'
      preLoaderRoute: typeof Sijagacai2Import
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/alert-system/configuration': {
      id: '/alert-system/configuration'
      path: '/alert-system/configuration'
      fullPath: '/alert-system/configuration'
      preLoaderRoute: typeof AlertSystemConfigurationImport
      parentRoute: typeof rootRoute
    }
    '/alert-system/history': {
      id: '/alert-system/history'
      path: '/alert-system/history'
      fullPath: '/alert-system/history'
      preLoaderRoute: typeof AlertSystemHistoryImport
      parentRoute: typeof rootRoute
    }
    '/sijagacai/$sijagacaiId': {
      id: '/sijagacai/$sijagacaiId'
      path: '/sijagacai/$sijagacaiId'
      fullPath: '/sijagacai/$sijagacaiId'
      preLoaderRoute: typeof SijagacaiSijagacaiIdImport
      parentRoute: typeof rootRoute
    }
    '/water-gate/$watergateId': {
      id: '/water-gate/$watergateId'
      path: '/water-gate/$watergateId'
      fullPath: '/water-gate/$watergateId'
      preLoaderRoute: typeof WaterGateWatergateIdImport
      parentRoute: typeof rootRoute
    }
    '/sijagacai/': {
      id: '/sijagacai/'
      path: '/sijagacai'
      fullPath: '/sijagacai'
      preLoaderRoute: typeof SijagacaiIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/water-gate/': {
      id: '/water-gate/'
      path: '/water-gate'
      fullPath: '/water-gate'
      preLoaderRoute: typeof WaterGateIndexImport
      parentRoute: typeof rootRoute
    }
    '/water-quality/': {
      id: '/water-quality/'
      path: '/water-quality'
      fullPath: '/water-quality'
      preLoaderRoute: typeof WaterQualityIndexImport
      parentRoute: typeof rootRoute
    }
    '/hidrology/rainfall/$rainfallId': {
      id: '/hidrology/rainfall/$rainfallId'
      path: '/hidrology/rainfall/$rainfallId'
      fullPath: '/hidrology/rainfall/$rainfallId'
      preLoaderRoute: typeof HidrologyRainfallRainfallIdImport
      parentRoute: typeof rootRoute
    }
    '/hidrology/water-level/$waterlevelId': {
      id: '/hidrology/water-level/$waterlevelId'
      path: '/hidrology/water-level/$waterlevelId'
      fullPath: '/hidrology/water-level/$waterlevelId'
      preLoaderRoute: typeof HidrologyWaterLevelWaterlevelIdImport
      parentRoute: typeof rootRoute
    }
    '/sijagacai/laporan-pemantauan/$laporanid': {
      id: '/sijagacai/laporan-pemantauan/$laporanid'
      path: '/sijagacai/laporan-pemantauan/$laporanid'
      fullPath: '/sijagacai/laporan-pemantauan/$laporanid'
      preLoaderRoute: typeof SijagacaiLaporanPemantauanLaporanidImport
      parentRoute: typeof rootRoute
    }
    '/hidrology/climatology/': {
      id: '/hidrology/climatology/'
      path: '/hidrology/climatology'
      fullPath: '/hidrology/climatology'
      preLoaderRoute: typeof HidrologyClimatologyIndexImport
      parentRoute: typeof rootRoute
    }
    '/hidrology/rainfall/': {
      id: '/hidrology/rainfall/'
      path: '/hidrology/rainfall'
      fullPath: '/hidrology/rainfall'
      preLoaderRoute: typeof HidrologyRainfallIndexImport
      parentRoute: typeof rootRoute
    }
    '/hidrology/water-level/': {
      id: '/hidrology/water-level/'
      path: '/hidrology/water-level'
      fullPath: '/hidrology/water-level'
      preLoaderRoute: typeof HidrologyWaterLevelIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-configuration': typeof AiConfigurationRoute
  '/alarm-history': typeof AlarmHistoryRoute
  '/assets-data': typeof AssetsDataRoute
  '/change-password': typeof ChangePasswordRoute
  '/change-pin': typeof ChangePinRoute
  '/employees-data': typeof EmployeesDataRoute
  '/infrastructure': typeof InfrastructureRoute
  '/jdih': typeof JdihRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/master-data': typeof MasterDataRoute
  '/permits-data': typeof PermitsDataRoute
  '/projects-data': typeof ProjectsDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password-pin': typeof SetPasswordPinRoute
  '/sijagacai2': typeof Sijagacai2Route
  '/welcome': typeof WelcomeRoute
  '/about': typeof AboutLazyRoute
  '/alert-system/configuration': typeof AlertSystemConfigurationRoute
  '/alert-system/history': typeof AlertSystemHistoryRoute
  '/sijagacai/$sijagacaiId': typeof SijagacaiSijagacaiIdRoute
  '/water-gate/$watergateId': typeof WaterGateWatergateIdRoute
  '/sijagacai': typeof SijagacaiIndexRoute
  '/users': typeof UsersIndexRoute
  '/water-gate': typeof WaterGateIndexRoute
  '/water-quality': typeof WaterQualityIndexRoute
  '/hidrology/rainfall/$rainfallId': typeof HidrologyRainfallRainfallIdRoute
  '/hidrology/water-level/$waterlevelId': typeof HidrologyWaterLevelWaterlevelIdRoute
  '/sijagacai/laporan-pemantauan/$laporanid': typeof SijagacaiLaporanPemantauanLaporanidRoute
  '/hidrology/climatology': typeof HidrologyClimatologyIndexRoute
  '/hidrology/rainfall': typeof HidrologyRainfallIndexRoute
  '/hidrology/water-level': typeof HidrologyWaterLevelIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-configuration': typeof AiConfigurationRoute
  '/alarm-history': typeof AlarmHistoryRoute
  '/assets-data': typeof AssetsDataRoute
  '/change-password': typeof ChangePasswordRoute
  '/change-pin': typeof ChangePinRoute
  '/employees-data': typeof EmployeesDataRoute
  '/infrastructure': typeof InfrastructureRoute
  '/jdih': typeof JdihRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/master-data': typeof MasterDataRoute
  '/permits-data': typeof PermitsDataRoute
  '/projects-data': typeof ProjectsDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password-pin': typeof SetPasswordPinRoute
  '/sijagacai2': typeof Sijagacai2Route
  '/welcome': typeof WelcomeRoute
  '/about': typeof AboutLazyRoute
  '/alert-system/configuration': typeof AlertSystemConfigurationRoute
  '/alert-system/history': typeof AlertSystemHistoryRoute
  '/sijagacai/$sijagacaiId': typeof SijagacaiSijagacaiIdRoute
  '/water-gate/$watergateId': typeof WaterGateWatergateIdRoute
  '/sijagacai': typeof SijagacaiIndexRoute
  '/users': typeof UsersIndexRoute
  '/water-gate': typeof WaterGateIndexRoute
  '/water-quality': typeof WaterQualityIndexRoute
  '/hidrology/rainfall/$rainfallId': typeof HidrologyRainfallRainfallIdRoute
  '/hidrology/water-level/$waterlevelId': typeof HidrologyWaterLevelWaterlevelIdRoute
  '/sijagacai/laporan-pemantauan/$laporanid': typeof SijagacaiLaporanPemantauanLaporanidRoute
  '/hidrology/climatology': typeof HidrologyClimatologyIndexRoute
  '/hidrology/rainfall': typeof HidrologyRainfallIndexRoute
  '/hidrology/water-level': typeof HidrologyWaterLevelIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ai-configuration': typeof AiConfigurationRoute
  '/alarm-history': typeof AlarmHistoryRoute
  '/assets-data': typeof AssetsDataRoute
  '/change-password': typeof ChangePasswordRoute
  '/change-pin': typeof ChangePinRoute
  '/employees-data': typeof EmployeesDataRoute
  '/infrastructure': typeof InfrastructureRoute
  '/jdih': typeof JdihRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/master-data': typeof MasterDataRoute
  '/permits-data': typeof PermitsDataRoute
  '/projects-data': typeof ProjectsDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password-pin': typeof SetPasswordPinRoute
  '/sijagacai2': typeof Sijagacai2Route
  '/welcome': typeof WelcomeRoute
  '/about': typeof AboutLazyRoute
  '/alert-system/configuration': typeof AlertSystemConfigurationRoute
  '/alert-system/history': typeof AlertSystemHistoryRoute
  '/sijagacai/$sijagacaiId': typeof SijagacaiSijagacaiIdRoute
  '/water-gate/$watergateId': typeof WaterGateWatergateIdRoute
  '/sijagacai/': typeof SijagacaiIndexRoute
  '/users/': typeof UsersIndexRoute
  '/water-gate/': typeof WaterGateIndexRoute
  '/water-quality/': typeof WaterQualityIndexRoute
  '/hidrology/rainfall/$rainfallId': typeof HidrologyRainfallRainfallIdRoute
  '/hidrology/water-level/$waterlevelId': typeof HidrologyWaterLevelWaterlevelIdRoute
  '/sijagacai/laporan-pemantauan/$laporanid': typeof SijagacaiLaporanPemantauanLaporanidRoute
  '/hidrology/climatology/': typeof HidrologyClimatologyIndexRoute
  '/hidrology/rainfall/': typeof HidrologyRainfallIndexRoute
  '/hidrology/water-level/': typeof HidrologyWaterLevelIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-configuration'
    | '/alarm-history'
    | '/assets-data'
    | '/change-password'
    | '/change-pin'
    | '/employees-data'
    | '/infrastructure'
    | '/jdih'
    | '/login'
    | '/map'
    | '/master-data'
    | '/permits-data'
    | '/projects-data'
    | '/reset-password'
    | '/set-password-pin'
    | '/sijagacai2'
    | '/welcome'
    | '/about'
    | '/alert-system/configuration'
    | '/alert-system/history'
    | '/sijagacai/$sijagacaiId'
    | '/water-gate/$watergateId'
    | '/sijagacai'
    | '/users'
    | '/water-gate'
    | '/water-quality'
    | '/hidrology/rainfall/$rainfallId'
    | '/hidrology/water-level/$waterlevelId'
    | '/sijagacai/laporan-pemantauan/$laporanid'
    | '/hidrology/climatology'
    | '/hidrology/rainfall'
    | '/hidrology/water-level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-configuration'
    | '/alarm-history'
    | '/assets-data'
    | '/change-password'
    | '/change-pin'
    | '/employees-data'
    | '/infrastructure'
    | '/jdih'
    | '/login'
    | '/map'
    | '/master-data'
    | '/permits-data'
    | '/projects-data'
    | '/reset-password'
    | '/set-password-pin'
    | '/sijagacai2'
    | '/welcome'
    | '/about'
    | '/alert-system/configuration'
    | '/alert-system/history'
    | '/sijagacai/$sijagacaiId'
    | '/water-gate/$watergateId'
    | '/sijagacai'
    | '/users'
    | '/water-gate'
    | '/water-quality'
    | '/hidrology/rainfall/$rainfallId'
    | '/hidrology/water-level/$waterlevelId'
    | '/sijagacai/laporan-pemantauan/$laporanid'
    | '/hidrology/climatology'
    | '/hidrology/rainfall'
    | '/hidrology/water-level'
  id:
    | '__root__'
    | '/'
    | '/ai-configuration'
    | '/alarm-history'
    | '/assets-data'
    | '/change-password'
    | '/change-pin'
    | '/employees-data'
    | '/infrastructure'
    | '/jdih'
    | '/login'
    | '/map'
    | '/master-data'
    | '/permits-data'
    | '/projects-data'
    | '/reset-password'
    | '/set-password-pin'
    | '/sijagacai2'
    | '/welcome'
    | '/about'
    | '/alert-system/configuration'
    | '/alert-system/history'
    | '/sijagacai/$sijagacaiId'
    | '/water-gate/$watergateId'
    | '/sijagacai/'
    | '/users/'
    | '/water-gate/'
    | '/water-quality/'
    | '/hidrology/rainfall/$rainfallId'
    | '/hidrology/water-level/$waterlevelId'
    | '/sijagacai/laporan-pemantauan/$laporanid'
    | '/hidrology/climatology/'
    | '/hidrology/rainfall/'
    | '/hidrology/water-level/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConfigurationRoute: typeof AiConfigurationRoute
  AlarmHistoryRoute: typeof AlarmHistoryRoute
  AssetsDataRoute: typeof AssetsDataRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ChangePinRoute: typeof ChangePinRoute
  EmployeesDataRoute: typeof EmployeesDataRoute
  InfrastructureRoute: typeof InfrastructureRoute
  JdihRoute: typeof JdihRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MasterDataRoute: typeof MasterDataRoute
  PermitsDataRoute: typeof PermitsDataRoute
  ProjectsDataRoute: typeof ProjectsDataRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordPinRoute: typeof SetPasswordPinRoute
  Sijagacai2Route: typeof Sijagacai2Route
  WelcomeRoute: typeof WelcomeRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AlertSystemConfigurationRoute: typeof AlertSystemConfigurationRoute
  AlertSystemHistoryRoute: typeof AlertSystemHistoryRoute
  SijagacaiSijagacaiIdRoute: typeof SijagacaiSijagacaiIdRoute
  WaterGateWatergateIdRoute: typeof WaterGateWatergateIdRoute
  SijagacaiIndexRoute: typeof SijagacaiIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  WaterGateIndexRoute: typeof WaterGateIndexRoute
  WaterQualityIndexRoute: typeof WaterQualityIndexRoute
  HidrologyRainfallRainfallIdRoute: typeof HidrologyRainfallRainfallIdRoute
  HidrologyWaterLevelWaterlevelIdRoute: typeof HidrologyWaterLevelWaterlevelIdRoute
  SijagacaiLaporanPemantauanLaporanidRoute: typeof SijagacaiLaporanPemantauanLaporanidRoute
  HidrologyClimatologyIndexRoute: typeof HidrologyClimatologyIndexRoute
  HidrologyRainfallIndexRoute: typeof HidrologyRainfallIndexRoute
  HidrologyWaterLevelIndexRoute: typeof HidrologyWaterLevelIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConfigurationRoute: AiConfigurationRoute,
  AlarmHistoryRoute: AlarmHistoryRoute,
  AssetsDataRoute: AssetsDataRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ChangePinRoute: ChangePinRoute,
  EmployeesDataRoute: EmployeesDataRoute,
  InfrastructureRoute: InfrastructureRoute,
  JdihRoute: JdihRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MasterDataRoute: MasterDataRoute,
  PermitsDataRoute: PermitsDataRoute,
  ProjectsDataRoute: ProjectsDataRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordPinRoute: SetPasswordPinRoute,
  Sijagacai2Route: Sijagacai2Route,
  WelcomeRoute: WelcomeRoute,
  AboutLazyRoute: AboutLazyRoute,
  AlertSystemConfigurationRoute: AlertSystemConfigurationRoute,
  AlertSystemHistoryRoute: AlertSystemHistoryRoute,
  SijagacaiSijagacaiIdRoute: SijagacaiSijagacaiIdRoute,
  WaterGateWatergateIdRoute: WaterGateWatergateIdRoute,
  SijagacaiIndexRoute: SijagacaiIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  WaterGateIndexRoute: WaterGateIndexRoute,
  WaterQualityIndexRoute: WaterQualityIndexRoute,
  HidrologyRainfallRainfallIdRoute: HidrologyRainfallRainfallIdRoute,
  HidrologyWaterLevelWaterlevelIdRoute: HidrologyWaterLevelWaterlevelIdRoute,
  SijagacaiLaporanPemantauanLaporanidRoute:
    SijagacaiLaporanPemantauanLaporanidRoute,
  HidrologyClimatologyIndexRoute: HidrologyClimatologyIndexRoute,
  HidrologyRainfallIndexRoute: HidrologyRainfallIndexRoute,
  HidrologyWaterLevelIndexRoute: HidrologyWaterLevelIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ai-configuration",
        "/alarm-history",
        "/assets-data",
        "/change-password",
        "/change-pin",
        "/employees-data",
        "/infrastructure",
        "/jdih",
        "/login",
        "/map",
        "/master-data",
        "/permits-data",
        "/projects-data",
        "/reset-password",
        "/set-password-pin",
        "/sijagacai2",
        "/welcome",
        "/about",
        "/alert-system/configuration",
        "/alert-system/history",
        "/sijagacai/$sijagacaiId",
        "/water-gate/$watergateId",
        "/sijagacai/",
        "/users/",
        "/water-gate/",
        "/water-quality/",
        "/hidrology/rainfall/$rainfallId",
        "/hidrology/water-level/$waterlevelId",
        "/sijagacai/laporan-pemantauan/$laporanid",
        "/hidrology/climatology/",
        "/hidrology/rainfall/",
        "/hidrology/water-level/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ai-configuration": {
      "filePath": "ai-configuration.tsx"
    },
    "/alarm-history": {
      "filePath": "alarm-history.tsx"
    },
    "/assets-data": {
      "filePath": "assets-data.tsx"
    },
    "/change-password": {
      "filePath": "change-password.tsx"
    },
    "/change-pin": {
      "filePath": "change-pin.tsx"
    },
    "/employees-data": {
      "filePath": "employees-data.tsx"
    },
    "/infrastructure": {
      "filePath": "infrastructure.tsx"
    },
    "/jdih": {
      "filePath": "jdih.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/master-data": {
      "filePath": "master-data.tsx"
    },
    "/permits-data": {
      "filePath": "permits-data.tsx"
    },
    "/projects-data": {
      "filePath": "projects-data.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/set-password-pin": {
      "filePath": "set-password-pin.tsx"
    },
    "/sijagacai2": {
      "filePath": "sijagacai2.tsx"
    },
    "/welcome": {
      "filePath": "welcome.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/alert-system/configuration": {
      "filePath": "alert-system/configuration.tsx"
    },
    "/alert-system/history": {
      "filePath": "alert-system/history.tsx"
    },
    "/sijagacai/$sijagacaiId": {
      "filePath": "sijagacai/$sijagacaiId.tsx"
    },
    "/water-gate/$watergateId": {
      "filePath": "water-gate/$watergateId.tsx"
    },
    "/sijagacai/": {
      "filePath": "sijagacai/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    },
    "/water-gate/": {
      "filePath": "water-gate/index.tsx"
    },
    "/water-quality/": {
      "filePath": "water-quality/index.tsx"
    },
    "/hidrology/rainfall/$rainfallId": {
      "filePath": "hidrology/rainfall/$rainfallId.tsx"
    },
    "/hidrology/water-level/$waterlevelId": {
      "filePath": "hidrology/water-level/$waterlevelId.tsx"
    },
    "/sijagacai/laporan-pemantauan/$laporanid": {
      "filePath": "sijagacai/laporan-pemantauan/$laporanid.tsx"
    },
    "/hidrology/climatology/": {
      "filePath": "hidrology/climatology/index.tsx"
    },
    "/hidrology/rainfall/": {
      "filePath": "hidrology/rainfall/index.tsx"
    },
    "/hidrology/water-level/": {
      "filePath": "hidrology/water-level/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
